version: '3.8'

services:
  discovery-server:
    build: ./microservices/discovery-server
    ports:
      - "8761:8761"
    networks:
      - booknest-network

  gateway-server:
    build: ./microservices/gateway-server
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    networks:
      - booknest-network

  auth-service:
    build: ./microservices/auth-service
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    networks:
      - booknest-network

  book-service:
    build: ./microservices/book-service
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    networks:
      - booknest-network

  cart-service:
    build: ./microservices/cart-service
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    networks:
      - booknest-network

  order-service:
    build: ./microservices/order-service
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    networks:
      - booknest-network

  wallet-service:
    build: ./microservices/wallet-service
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    networks:
      - booknest-network

networks:
  booknest-network:
    driver: bridge
